### PR TITLE
README.md improvements

### PR DESCRIPTION
**Pull request by ricotries15**
Readability and content improvements to the `README.md`.

There is one thing I completely removed, under `## USAGE > ### Managing Customers` you said the following:
"-Customers can also be similarly edited, by providing the customer ID."

I looked at the scripts and could not find any functions or code that allows you to modify an existing customer, especially not the `-ac` option.

### CODE REVIEW

**Comment by realchonk** [comment]
If you want to modify a customer with the -ac option you just use the pre-existing CID.
I probably should've written that.

**Comment by realchonk** [comment]
But thanks to your contribution, I could've never done it so great as you did.
Now this project has good documentation.
I'm thankful to what you did.

**Comment by ricotries15** [comment]
Under `accounthing.sh`:
```
-ac)
   cdb_add_i
   ret="$?"
   ;;
```

Does not take positional parameters.

**Comment by realchonk** [comment]
I meant that, when this prompt ```ID [003]: ``` comes up, you can specify an existing CID and then get all of the details pre-applied.

**Comment by realchonk** [comment]
Try it, create a customer. Then try to create a new one with the same CID.

**Comment by ricotries15** [comment]
So you'd have to be more clear that the interactive prompt can be used to update an existing customer since it looks for an existing CID before making changes. The wording is the key here.

**Comment by realchonk** [comment]
Yes, I agree. I'm not particularly good at documentation. Just look at my other projects...

**Comment by ricotries15** [comment]
I read the function for the interactive creation and I see what you mean, just got to be more clear in how customers can be edited. I'll add the change before you pull, let me know if it makes sense.

**Comment by realchonk** [comment]
Ok

**Comment by ricotries15** [comment]
That's it for this request! I have no more edits unless you have any recommendations.

**Comment by realchonk** [comment]
No man, thanks. You did a great job and I'm thankful.

**Pull request merged**
